version: '3.7'
services:
  api:
    build:
      context: ./api
      target: base
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5022:3333"
